# -*- coding: utf-8 -*-
"""
Created on Wed Sep 21 14:48:05 2022

@author: Pierre Boniface
"""

def initialize_rules(L):                                                       # L being the length of the search window

    rul = []                                                                   # Empty list to be filled with sequential pinary numbers
    res = [0] * 2**L                                                           # WIP genome to be generated by evo
    n=0

    for _ in range(2**L):
        rul.append(format(n, ('0' + str(L) + 'b')))                            # Appends n in binary format to list of rules, example format; '03b', where 0 indicates leading zeroes, 3 is L (window length) in string form, and b indicates binary
        n = n+1

    rules = dict(zip(rul,res))                                                 # Merges the list of rules with the list of outcomes

    print(rules)

    return rules


initialize_rules(3)